// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package main

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID            pgtype.UUID
	Name          string
	Currency      string
	Balance       int64
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeactivatedAt pgtype.Timestamptz
	Type          string
}

type Entry struct {
	ID            pgtype.UUID
	AccountID     pgtype.UUID
	TransactionID pgtype.UUID
	Direction     string
	Amount        int64
	CreatedAt     pgtype.Timestamptz
}

type Transaction struct {
	ID             pgtype.UUID
	IdempotencyKey string
	AccountID      pgtype.UUID
	Amount         int64
	CreatedAt      pgtype.Timestamptz
}
