// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package main

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findAccountById = `-- name: findAccountById :one
SELECT id, name, currency, balance, created_at, updated_at, deactivated_at, type FROM accounts WHERE id = $1
`

func (q *Queries) findAccountById(ctx context.Context, id pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, findAccountById, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Currency,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeactivatedAt,
		&i.Type,
	)
	return i, err
}

const findAccountByIdForUpdate = `-- name: findAccountByIdForUpdate :one
SELECT id, name, currency, balance, created_at, updated_at, deactivated_at, type FROM accounts WHERE id = $1 FOR UPDATE
`

func (q *Queries) findAccountByIdForUpdate(ctx context.Context, id pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, findAccountByIdForUpdate, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Currency,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeactivatedAt,
		&i.Type,
	)
	return i, err
}

const insertAccount = `-- name: insertAccount :one
INSERT INTO accounts (name, currency, balance)
VALUES ($1, $2, $3)
RETURNING id, name, currency, balance, created_at
`

type insertAccountParams struct {
	Name     string
	Currency string
	Balance  int64
}

type insertAccountRow struct {
	ID        pgtype.UUID
	Name      string
	Currency  string
	Balance   int64
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) insertAccount(ctx context.Context, arg insertAccountParams) (insertAccountRow, error) {
	row := q.db.QueryRow(ctx, insertAccount, arg.Name, arg.Currency, arg.Balance)
	var i insertAccountRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Currency,
		&i.Balance,
		&i.CreatedAt,
	)
	return i, err
}

const insertEntry = `-- name: insertEntry :one
INSERT INTO entries (account_id, journal_id, direction, amount)
VALUES ($1, $2, $3, $4)
RETURNING id, account_id, journal_id, direction, amount, created_at
`

type insertEntryParams struct {
	AccountID pgtype.UUID
	JournalID pgtype.UUID
	Direction string
	Amount    int64
}

func (q *Queries) insertEntry(ctx context.Context, arg insertEntryParams) (Entry, error) {
	row := q.db.QueryRow(ctx, insertEntry,
		arg.AccountID,
		arg.JournalID,
		arg.Direction,
		arg.Amount,
	)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.JournalID,
		&i.Direction,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const insertJournal = `-- name: insertJournal :one
INSERT INTO journal (idempotency_key, account_id, amount)
VALUES ($1, $2, $3)
RETURNING id, idempotency_key, account_id, amount, created_at
`

type insertJournalParams struct {
	IdempotencyKey string
	AccountID      pgtype.UUID
	Amount         int64
}

func (q *Queries) insertJournal(ctx context.Context, arg insertJournalParams) (Journal, error) {
	row := q.db.QueryRow(ctx, insertJournal, arg.IdempotencyKey, arg.AccountID, arg.Amount)
	var i Journal
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.AccountID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const updateAccountBalance = `-- name: updateAccountBalance :exec
UPDATE accounts SET balance = balance + $1 WHERE id = $2
`

type updateAccountBalanceParams struct {
	Balance int64
	ID      pgtype.UUID
}

func (q *Queries) updateAccountBalance(ctx context.Context, arg updateAccountBalanceParams) error {
	_, err := q.db.Exec(ctx, updateAccountBalance, arg.Balance, arg.ID)
	return err
}
