// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package main

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findAccountById = `-- name: findAccountById :one
SELECT id, name, currency, balance, balance_version, created_at, updated_at, deactivated_at, type FROM accounts WHERE id = $1
`

func (q *Queries) findAccountById(ctx context.Context, id pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, findAccountById, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Currency,
		&i.Balance,
		&i.BalanceVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeactivatedAt,
		&i.Type,
	)
	return i, err
}

const findAccountByIdForUpdate = `-- name: findAccountByIdForUpdate :one
SELECT id, name, currency, balance, balance_version, created_at, updated_at, deactivated_at, type FROM accounts WHERE id = $1 FOR UPDATE
`

func (q *Queries) findAccountByIdForUpdate(ctx context.Context, id pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, findAccountByIdForUpdate, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Currency,
		&i.Balance,
		&i.BalanceVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeactivatedAt,
		&i.Type,
	)
	return i, err
}

const findOutboxByStatus = `-- name: findOutboxByStatus :many
SELECT id, source, source_id, attempts, status, payload, published_at, created_at FROM outbox WHERE status = $1
`

func (q *Queries) findOutboxByStatus(ctx context.Context, status string) ([]Outbox, error) {
	rows, err := q.db.Query(ctx, findOutboxByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Outbox
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.SourceID,
			&i.Attempts,
			&i.Status,
			&i.Payload,
			&i.PublishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAccount = `-- name: insertAccount :one
INSERT INTO accounts (name, currency, balance)
VALUES ($1, $2, $3)
RETURNING id, name, currency, balance, created_at
`

type insertAccountParams struct {
	Name     string
	Currency string
	Balance  int64
}

type insertAccountRow struct {
	ID        pgtype.UUID
	Name      string
	Currency  string
	Balance   int64
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) insertAccount(ctx context.Context, arg insertAccountParams) (insertAccountRow, error) {
	row := q.db.QueryRow(ctx, insertAccount, arg.Name, arg.Currency, arg.Balance)
	var i insertAccountRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Currency,
		&i.Balance,
		&i.CreatedAt,
	)
	return i, err
}

const insertEntry = `-- name: insertEntry :one
INSERT INTO entries (account_id, journal_id, direction, amount)
VALUES ($1, $2, $3, $4)
RETURNING id, account_id, journal_id, direction, amount, created_at
`

type insertEntryParams struct {
	AccountID pgtype.UUID
	JournalID pgtype.UUID
	Direction string
	Amount    int64
}

func (q *Queries) insertEntry(ctx context.Context, arg insertEntryParams) (Entry, error) {
	row := q.db.QueryRow(ctx, insertEntry,
		arg.AccountID,
		arg.JournalID,
		arg.Direction,
		arg.Amount,
	)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.JournalID,
		&i.Direction,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const insertJournal = `-- name: insertJournal :one
INSERT INTO journal (idempotency_key, account_id, amount)
VALUES ($1, $2, $3)
RETURNING id, idempotency_key, account_id, amount, created_at
`

type insertJournalParams struct {
	IdempotencyKey string
	AccountID      pgtype.UUID
	Amount         int64
}

func (q *Queries) insertJournal(ctx context.Context, arg insertJournalParams) (Journal, error) {
	row := q.db.QueryRow(ctx, insertJournal, arg.IdempotencyKey, arg.AccountID, arg.Amount)
	var i Journal
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.AccountID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const insertOutbox = `-- name: insertOutbox :one
INSERT INTO outbox (source, source_id, payload)
VALUES ($1, $2, $3)
RETURNING id, source, source_id, status, payload, created_at
`

type insertOutboxParams struct {
	Source   string
	SourceID string
	Payload  []byte
}

type insertOutboxRow struct {
	ID        pgtype.UUID
	Source    string
	SourceID  string
	Status    string
	Payload   []byte
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) insertOutbox(ctx context.Context, arg insertOutboxParams) (insertOutboxRow, error) {
	row := q.db.QueryRow(ctx, insertOutbox, arg.Source, arg.SourceID, arg.Payload)
	var i insertOutboxRow
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.SourceID,
		&i.Status,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const updateAccountBalance = `-- name: updateAccountBalance :one
UPDATE accounts SET balance = balance + $1, balance_version = balance_version + 1 WHERE id = $2
RETURNING id, name, currency, balance, balance_version, created_at, updated_at, deactivated_at, type
`

type updateAccountBalanceParams struct {
	Balance int64
	ID      pgtype.UUID
}

func (q *Queries) updateAccountBalance(ctx context.Context, arg updateAccountBalanceParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccountBalance, arg.Balance, arg.ID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Currency,
		&i.Balance,
		&i.BalanceVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeactivatedAt,
		&i.Type,
	)
	return i, err
}

const updateOutboxStatus = `-- name: updateOutboxStatus :exec
UPDATE outbox SET status = $1, published_at = now() WHERE id = $2
`

type updateOutboxStatusParams struct {
	Status string
	ID     pgtype.UUID
}

func (q *Queries) updateOutboxStatus(ctx context.Context, arg updateOutboxStatusParams) error {
	_, err := q.db.Exec(ctx, updateOutboxStatus, arg.Status, arg.ID)
	return err
}
